// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
Console.WriteLine("Sema");
Console.WriteLine("Mert");
Console.WriteLine("Emrecan");
Console.WriteLine("Ali Erhan");
Console.WriteLine("Mesut");
Console.WriteLine("Ahmet");
Console.WriteLine("Can");
Console.WriteLine("Yağızhan");
Console.WriteLine("Serkan");
Console.WriteLine("Yağızhan");
Console.WriteLine("Can");
Console.WriteLine("Talha");
Console.WriteLine("Elif");
Console.WriteLine("Talha");
Console.WriteLine("C");
Console.WriteLine("A");
Console.WriteLine("N");
Console.WriteLine("Talha");